CREATE TABLE colecoes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    estudio_id INT UNSIGNED NOT NULL,
    nome VARCHAR(150) NOT NULL,
    ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    usuario_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (estudio_id) REFERENCES estudios(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;