CREATE TABLE custos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	produto_id INT UNSIGNED NOT NULL,
	custo_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	custo_por_unidade DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE KEY uk_custos_produto (produto_id),
	CONSTRAINT fk_custos_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
