CREATE TABLE impressoes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    produto_id INT UNSIGNED NOT NULL,
    impressora_id INT UNSIGNED NOT NULL,
    tempo_impressao INT NOT NULL,
    unidades_produzidas INT NOT NULL,
    markup INT NOT NULL,
    taxa_falha INT NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    valor_energia DECIMAL(10,8),
    peso_material INT NOT NULL,
    custo_material DECIMAL(10,2),
    custo_lavagem_alcool DECIMAL(10,2),
    custo_energia DECIMAL(10,2),
    depreciacao DECIMAL(10,2),
    custo_total_impressao DECIMAL(10,2),
    custo_por_unidade DECIMAL(10,2),
    lucro_total_impressao DECIMAL(10,2),
    lucro_por_unidade DECIMAL(10,2),
    porcentagem_lucro INT,
    preco_venda_sugerido DECIMAL(10,2),
    preco_venda_sugerido_unidade DECIMAL(10,2),
    observacoes TEXT,
    usuario_id INT UNSIGNED NOT NULL,
    filamento_id INT UNSIGNED NULL,
    resina_id INT UNSIGNED NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
    FOREIGN KEY (impressora_id) REFERENCES impressoras(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (filamento_id) REFERENCES filamento(id) ON DELETE CASCADE,
    FOREIGN KEY (resina_id) REFERENCES resinas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;