CREATE TABLE impressoes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    estudio_id INT UNSIGNED,
    colecao_id INT UNSIGNED,
    nome_original VARCHAR(150),
    arquivo_impressao VARCHAR(255),
    impressora_id INT UNSIGNED NOT NULL,
    material_id INT UNSIGNED NOT NULL,
    tempo_impressao INT NOT NULL,
    imagem_capa VARCHAR(255),
    unidades_produzidas INT NOT NULL,
    margem_lucro INT NOT NULL,
    taxa_falha INT NOT NULL,
    componente INT,
    imagens_impressao INT,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    valor_energia DECIMAL(10,8) NOT NULL,
    peso_material INT NOT NULL,
    custo_material DECIMAL(10,2) NOT NULL,
    custo_lavagem_alcool DECIMAL(10,2),
    custo_energia DECIMAL(10,2) NOT NULL,
    depreciacao DECIMAL(10,2) NOT NULL,
    custo_total_impressao DECIMAL(10,2) NOT NULL,
    custo_por_unidade DECIMAL(10,2) NOT NULL,
    lucro DECIMAL(10,2) NOT NULL,
    porcentagem_lucro INT NOT NULL,
    preco_venda_sugerido DECIMAL(10,2) NOT NULL,
    preco_venda_sugerido_unidade DECIMAL(10,2) NOT NULL,
    observacoes TEXT,
    sku VARCHAR(50) UNIQUE,
    usuario_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (estudio_id) REFERENCES estudios(id) ON DELETE SET NULL,
    FOREIGN KEY (colecao_id) REFERENCES colecoes(id) ON DELETE SET NULL,
    FOREIGN KEY (impressora_id) REFERENCES impressoras(id) ON DELETE CASCADE,
    FOREIGN KEY (material_id) REFERENCES filamento(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;