CREATE TABLE mapas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_sku VARCHAR(50) NOT NULL,
    produto_id INT UNSIGNED NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT NULL,
    link_compra VARCHAR(500) NULL,
    imagem_capa VARCHAR(255) NULL,
    imagens TEXT NULL,
    formato_grade VARCHAR(100) NOT NULL,
    largura DECIMAL(10,2) NOT NULL,
    comprimento DECIMAL(10,2) NOT NULL,
    material VARCHAR(120) NOT NULL,
    fornecedor_id INT UNSIGNED NULL,
    unidades_produzidas INT UNSIGNED NOT NULL DEFAULT 1,
    ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    usuario_id INT UNSIGNED NOT NULL,
    UNIQUE KEY uk_mapas_sku_usuario (id_sku, usuario_id),
    INDEX idx_mapas_produto_id (produto_id),
    INDEX idx_mapas_fornecedor_id (fornecedor_id),
    CONSTRAINT fk_mapas_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_mapas_sku FOREIGN KEY (id_sku, usuario_id) REFERENCES sku(sku, usuario_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
