CREATE TABLE produtos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sku INT UNSIGNED NOT NULL,
	categoria INT UNSIGNED NOT NULL,
	imagem_capa VARCHAR(255) NULL,
	imagens TEXT NULL,
	descricao TEXT NULL,
	custo INT UNSIGNED NOT NULL,
	markup_lojista DECIMAL(10,2) NOT NULL,
	markup_consumidor_final DECIMAL(10,2) NOT NULL,
	preco_lojista DECIMAL(10,2) NOT NULL,
	preco_consumidor_final DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (sku) REFERENCES sku(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (custo) REFERENCES custos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (categoria) REFERENCES categorias(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
