CREATE TABLE produtos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	usuario_id INT UNSIGNED NOT NULL,
	nome VARCHAR(150),
	categoria INT UNSIGNED NOT NULL,
	imagem_capa VARCHAR(255) NULL,
	imagens TEXT NULL,
	descricao TEXT NULL,
	markup DECIMAL(10,2) NOT NULL,
	preco_lojista DECIMAL(10,2) NOT NULL,
	preco_consumidor_final DECIMAL(10,2) NOT NULL,
	data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_produtos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_produtos_categoria FOREIGN KEY (categoria) REFERENCES categorias(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
