CREATE TABLE sku (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sku VARCHAR(50) NOT NULL,
	data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	usuario_id INT UNSIGNED NOT NULL,
	UNIQUE KEY uk_sku_usuario (sku, usuario_id),
	FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

