CREATE TABLE sku (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	produto_id INT UNSIGNED NOT NULL,
	sku VARCHAR(50) NOT NULL,
	data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ultima_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	usuario_id INT UNSIGNED NOT NULL,
	UNIQUE KEY uk_sku_produto (produto_id),
	UNIQUE KEY uk_sku_usuario (sku, usuario_id),
	CONSTRAINT fk_sku_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_sku_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

