CREATE TABLE IF NOT EXISTS torres (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	id_sku VARCHAR(50) NULL,
	produto_id INT UNSIGNED NOT NULL,
	usuario_id INT UNSIGNED NOT NULL,
	id_impressao INT UNSIGNED NULL,
	nome_original VARCHAR(150) NULL,
	id_estudio INT UNSIGNED NULL,
	id_colecao INT UNSIGNED NULL,
	tematica VARCHAR(50) NULL,
	capa VARCHAR(255) NULL,
	imagens TEXT NULL,
	outras_caracteristicas TEXT NULL,
	data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_torres_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_torres_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_torres_impressao FOREIGN KEY (id_impressao) REFERENCES impressoes(id) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT fk_torres_estudio FOREIGN KEY (id_estudio) REFERENCES estudios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_torres_colecao FOREIGN KEY (id_colecao) REFERENCES colecoes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT fk_torres_sku FOREIGN KEY (id_sku, usuario_id) REFERENCES sku(sku, usuario_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	UNIQUE KEY uk_torres_sku_usuario (id_sku, usuario_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
